# Generated by Django 2.1.5 on 2019-03-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
